services:
  worker-high:
    build:
      context: ..
      dockerfile: worker/Dockerfile.worker
      network: host
    env_file:
      - ./env/variables.worker.env
    environment:
      - CELERY_QUEUES=video.high,video.all
    #container_name: worker-high
    profiles:
      - worker-high
    depends_on:
      - rabbitmq
      - seaweedfs
      - valkey
    deploy:
      replicas: 2
    dns:
      - 1.1.1.1
      - 8.8.8.8
  worker-low:
    build:
      context: ..
      dockerfile: worker/Dockerfile.worker
      network: host
    #container_name: worker-low
    profiles:
      - worker-low
    env_file:
      - ./env/variables.worker.env
    environment:
      - CELERY_QUEUES=video.low,video.all
    depends_on:
      - rabbitmq
      - seaweedfs
      - valkey
    deploy:
      replicas: 2
    dns:
      - 1.1.1.1
      - 8.8.8.8