FROM bensuperpc/multimedia:1.0.0-archlinux-base

WORKDIR /app

RUN pacman-key --init && pacman -Sy archlinux-keyring --noconfirm && pacman -Syu --noconfirm && \
    pacman -S --noconfirm python-pip && \
    pacman -Scc --noconfirm

COPY requirements.txt .
RUN pip install --break-system-packages -r requirements.txt

WORKDIR /app

COPY start_worker.py start_worker.py

ENTRYPOINT ["python3", "start_worker.py"]