services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    profiles:
      - rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./env/variables.rabbitmq.env
