services:
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile.api
      network: host
    container_name: api
    profiles:
      - api
    ports:
      - "5500:5500"
    env_file:
      - ./env/variables.api.env
    depends_on:
      - rabbitmq
      - minio
      - valkey
    dns:
      - 1.1.1.1
      - 8.8.8.8
